### ISSUE TITLE
tool truncating file locations.

### ISSUE THREAD

**Issue by CodeNameTheOnlyOne** [cert-lv/exchange_webshell_detection#6]
tool works great but it is not giving the full path for the frontend logs
ie 
Found suspicious files in Exchange frontend dir and they match functions used by known webshells:

C:\Program Files\Microsoft\Exchange Server\V15\Frontend\... 3/3/2021 12:50:31 AM
C:\Program Files\Microsoft\Exchange Server\V15\Frontend\... 3/3/2021 3:52:58 AM

not sure the proper way to fix this but i added |ft -wrap  to the select-object.
ie     Get-ChildItem $matches.Path | Select-Object FullName, LastWriteTime |ft -wrap 

just thought i would add this.
Thanks for the tool.

**Comment by ghost** [comment]
Thank you for the suggestion, implemented!
