### ISSUE TITLE
MS Defender issue

### ISSUE THREAD

**Issue by FlorianHeigl** [cert-lv/exchange_webshell_detection#7]
Could you contact MS to get this whitelisted?

I have one SMB client that is unnerved(*) by Defender blocking the detection script's execution.
I suppose there's more cases like this than we could imagine.
Maybe there's a way you can at least sign the script?

(They didn't worry putting a MS box on the internet, though)

**Comment by ghost** [comment]
Hi Florian,

Please run the Microsoft Safety Scanner and Test-Proxylogon.ps1 published by Microsoft: https://github.com/microsoft/CSS-Exchange/tree/main/Security , they have now incorporated webshell detection.

I will discontinue this project shortly.
